### ISSUE TITLE
PHP 7.1 Upgrade

### ISSUE THREAD

**Issue by dextervip** [eclipse/che-dockerfiles#113]
Hey,
It would great to upgrade PHP to 7.1 as some libraries are already requiring it. Latest doctrine/dbal requires php: ^7.1

**Comment by bmicklea** [comment]
@eivantsov is this something that can be done in a custom stack?

**Comment by eivantsov** [comment]
Maybe our PHP stack can be upgraded to 7.1. But yes, once can create own custom stack with PHP 7.1
