### ISSUE TITLE
[.NET Core 2.0] Add CentOS based stack for .NET Core 2.0

### ISSUE THREAD

**Issue by omajid** [eclipse/che-dockerfiles#125]
Can we add/switch to a CentOS (or RHEL) based .NET Core 2.0 stack? RHEL (and CentOS) builds are being built from source rather than the binary Microsoft distributes for Ubuntu and other platforms.

cc @dharmit

**Comment by dharmit** [comment]
@omajid It'll take a day or two before the RPMs hit CentOS repos. I'll start working on this once the RPMs are in.

**Comment by eivantsov** [comment]
@dharmit will you do it or do you expect me to provide a PR?

**Comment by l0rd** [comment]
Hello @dharmit what is the status for this issue? Can we help?

**Comment by l0rd** [comment]
Thanks @dharmit. Should we do an exception for .NET Core 2.0 and use testing repo for this image?  @kbsingh what do you think?

**Comment by dharmit** [comment]
@l0rd the RPMs should be available shortly. Since we've waited for quite long already, I'd recommend we give it a day more. Otherwise, I'll get the image up with testing RPMs for time being.

**Comment by omajid** [comment]
Thanks to @kbsingh we now have .NET Core RPMs as part of CentOS:

1. `yum install centos-release-dotnet`
2. `yum install rh-dotnet10`
3. `scl enable rh-dotnet20 bash`
4. `dotnet --info`

**Comment by eivantsov** [comment]
We'll need dotnet in `$PATH` since languageserver will call it.

**Comment by dharmit** [comment]
@eivantsov that should be in the path because of `cat /opt/rh/rh-dotnet20/enable >> /home/user/.bashrc` instruction in the Dockerfile. When we spin up a container, doing `dotnet --version` just works. Does that help for language server purpose?

**Comment by eivantsov** [comment]
@dharmit  adding it to ~/.bashrc does not always work when doing execs. It should be rather added to PATH in Dockerfile ENV instruction.

**Comment by dharmit** [comment]
@eivantsov I've updated the PR to have the instruction: `ENV PATH /opt/rh/rh-dotnet20/root/usr/bin:/opt/rh/rh-dotnet20/root/usr/sbin${PATH:+:${PATH}}` which is basically same as that in `/opt/rh/rh-dotnet20/enable`.

Before:
```bash
$ docker run -it --rm registry.centos.org/che-stacks/centos-dotnet20 dotnet --version
/usr/bin/docker-latest: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"dotnet\": executable file not found in $PATH".
ERRO[0005] error getting events from daemon: context canceled
```

After:
```bash
$ docker run -it --rm registry.centos.org/che-stacks/centos-dotnet20 dotnet --version
2.0.0
```

**Comment by omajid** [comment]
@dharmit Can we someone invoke `scl enable` directly? (Or by sourcing`scl_enable` file)? There are known differences between adding the binary to `PATH` vs invoking scl. Some differences include:

- Telemetry: `scl enable` disables this, invoking `/opt/rh/rh-dotnet20/root/usr/bin/dotnet` doesnt.
- Differnet `libcurl`: Invoking `/opt/rh/rh-dotnet20/root/usr/bin/dotnet` uses the libcurl under `/usr/lib64`, which is an older version linked against nss rather than openssl. It also means some features (such as client certificates) in .NET Core will not work.

The official containers ([repo here](https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0)) published for RHEL work around this by: 

- Adding an `ENTRYPOINT` that always gets called
- Adding environment variables so bash can invoke `scl enable` automatically
- Making the entrypoint invoke a shell script so a bash instance is spawned and reads those environment variables to run `scl_enable`.

Now users can do `dotnet --info` (for example) and it works without any other commands.

In general, it would be great if you could stay close to https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.0/runtime/Dockerfile.rhel7 to pick up many fixes and features.

**Comment by omajid** [comment]
Sounds like https://github.com/dotnet/source-build/issues/125

**Comment by eivantsov** [comment]
Yes, it does. Should we wait for the fix then?

**Comment by omajid** [comment]
Okay. I don't have an ETA for a fix right now.

**Comment by omajid** [comment]
@eivantsov What version/release/binary of omnisharp are you using?

Hey, @mickaelistria! I seem to recall you using the source-built `dotnet` packages on Fedora 26 and it worked with aCute/omnisharp in your experiments. Do you know why it wont work on CentOS? Does it have to do with bundled mono by omnisharp folks?

**Comment by mickaelistria** [comment]
I tried the packages, but as OmniSharp was asking for a more recent version in order to drop the dependency on mono, I switched to the binary archive provided by the dotnet-core project. I haven't try the Fedora package for a while.

**Comment by eivantsov** [comment]
@omajid 
```
  "name": "omnisharp-client",
  "omnisharp-roslyn": "v1.22.0"

...

"_id": "omnisharp-client@7.0.7"
```

**Comment by omajid** [comment]
@eivantsov Thanks. I manged to reproduce this locally with `omnisharp-roslyn` + `omnisharp-emacs` too.

**Comment by tmds** [comment]
@eivantsov To get omnisharp to work with _source-build_ .NET Core on Fedora I'm adding a symlink so mono uses the netcoreapp1.0 assembly (which is present) instead of trying to use the net46 assembly (which isn't). With this symlink vscode loads my project and provides intellisense. Can you add that to the Dockerfile and see how it works for you?

`ln -s /opt/rh/rh-dotnet20/root/usr/bin/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/tools/netcoreapp1.0 /opt/rh/rh-dotnet20/root/usr/bin/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/tools/net46`

**Comment by eivantsov** [comment]
@tmds thanks! will give it a shot now

**Comment by l0rd** [comment]
@tmds 
```
/opt/rh/rh-dotnet20/root/usr/bin/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/tools/netcoreapp1.0
```
doesn't exist. Did you mean
```
/opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/tools/netcoreapp1.0
```
?

Anyway adding:
```Dockerfile
sudo ln -s /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/tools/netcoreapp1.0 /opt/rh/rh-dotnet20/root/usr/lib64/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/tools/net46
```
doesn't work for me.

**Comment by tmds** [comment]
> Did you mean

Yes

> sudo 

Why sudo? Is this in a Dockerfile?

> doesn't work for me.

What does it do?
e.g. when I use this in vscode, I can navigate to the "Omnisharp log" and I see the project not loading due to the missing net46. Then when I add the symlink, the project loads fine.
Is there some logging you can share?

**Comment by l0rd** [comment]
@tmds I am not able to see OmniSharp logs when starting the LS using Che but when I try to start it manually:

```bash
SRC=/projects/dotnet-web-simple
OS_CLIENT_PID=532
./OmniSharp --stdio --zero-based-indices \
                      -s ${SRC} --hostPID ${OS_CLIENT_PID} \
                      --dotnet:enablePackageRestore=true -v
```

I can see the following errors in the logs:

```json
{
    "Event": "log",
    "Body": {
        "LogLevel": "ERROR",
        "Name": "OmniSharp.MSBuild.ProjectFile.ProjectFileInfo",
        "Message": "The \"ReportAssetsLogMessages\" task failed unexpectedly.\nSystem.IO.FileLoadException: Could not load file or assembly 'NuGet.ProjectModel, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)\nFile name: 'NuGet.ProjectModel, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'\n   at Microsoft.NET.Build.Tasks.ReportAssetsLogMessages.ExecuteCore()\n   at Microsoft.NET.Build.Tasks.TaskBase.Execute()\n   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()"
    },
    "Seq": 23,
    "Type": "event"
}
{
    "Event": "log",
    "Body": {
        "LogLevel": "ERROR",
        "Name": "OmniSharp.MSBuild.ProjectFile.ProjectFileInfo",
        "Message": "The \"CheckForTargetInAssetsFile\" task failed unexpectedly.\nSystem.IO.FileLoadException: Could not load file or assembly 'NuGet.ProjectModel, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)\nFile name: 'NuGet.ProjectModel, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'\n   at Microsoft.NET.Build.Tasks.CheckForTargetInAssetsFile.ExecuteCore()\n   at Microsoft.NET.Build.Tasks.TaskBase.Execute()\n   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\n   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()"
    },
    "Seq": 24,
    "Type": "event"
}
```

**Comment by l0rd** [comment]
For testing I am using [dotnet-web-simple](https://github.com/che-samples/dotnet-web-simple) and OmniSharp [v1.22.0](https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.22.0)

**Comment by tmds** [comment]
> For testing I am using dotnet-web-simple and OmniSharp v1.22.0

I was not sure what package to pick for v1.22.0. So I went to the latest version v1.25.0 and used omnisharp-linux-x64.tar.gz. (This is the stdio package, there is also an http package.)

Then on RHEL7 (not in docker), I added the symlink (net46 -> netcoreapp1.0) and created a console project at /tmp/che125/console.

Starting OmniSharp picks up the project:
```
$ ./run -s /tmp/che125/console --stdio
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Initializing in /tmp/che125/console"},"Seq":1,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Auto package restore: False"},"Seq":2,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Update workspace context"},"Seq":3,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Resolving projects references"},"Seq":4,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.MSBuildProjectSystem","Message":"Omnisharp will use local MSBuild.\n    MSBUILD_EXE_PATH: /tmp/che125/omnisharp2/omnisharp/msbuild/MSBuild.dll\n    MSBuildExtensionsPath: /tmp/che125/omnisharp2/omnisharp/msbuild\n    RoslynTargetsPath: /tmp/che125/omnisharp2/omnisharp/msbuild/Roslyn\n    CscToolPath: /tmp/che125/omnisharp2/omnisharp/msbuild/Roslyn\n"},"Seq":5,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.MSBuildProjectSystem","Message":"No solution files found in '/tmp/che125/console'"},"Seq":6,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.MSBuildProjectSystem","Message":"Loading project: /tmp/che125/console/console.csproj"},"Seq":7,"Type":"event"}
{"Event":"MsBuildProjectDiagnostics","Body":{"FileName":"/tmp/che125/console/console.csproj","Warnings":[],"Errors":[]},"Seq":8,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.MSBuildProjectSystem","Message":"Update project: console"},"Seq":9,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Script.ScriptProjectSystem","Message":"Detecting CSX files in '/tmp/che125/console'."},"Seq":10,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Script.ScriptProjectSystem","Message":"Could not find any CSX files"},"Seq":11,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Stdio.Program","Message":"Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider"},"Seq":12,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Stdio.Program","Message":"Configuration finished."},"Seq":13,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Stdio.Program","Message":"Omnisharp server running using Stdio at location '/tmp/che125/console' on host -1."},"Seq":14,"Type":"event"}
{"Event":"started","Body":null,"Seq":15,"Type":"event"}
{"Event":"ProjectAdded","Body":{"MsBuildProject":{"ProjectGuid":"00000000-0000-0000-0000-000000000000","Path":"/tmp/che125/console/console.csproj","AssemblyName":"console","TargetPath":"/tmp/che125/console/bin/Debug/netcoreapp2.0/console.dll","TargetFramework":".NETCoreApp,Version=v2.0","SourceFiles":["/tmp/che125/console/Program.cs","/tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs","/tmp/che125/console/obj/Debug/netcoreapp2.0/console.AssemblyInfo.cs"],"TargetFrameworks":[{"Name":".NETCoreApp","FriendlyName":".NETCoreApp","ShortName":"netcoreapp2.0"}],"OutputPath":"bin\\Debug\\netcoreapp2.0\\","IsExe":true,"IsUnityProject":false}},"Seq":16,"Type":"event"}
{"Event":"ProjectChanged","Body":{"MsBuildProject":{"ProjectGuid":"00000000-0000-0000-0000-000000000000","Path":"/tmp/che125/console/console.csproj","AssemblyName":"console","TargetPath":"/tmp/che125/console/bin/Debug/netcoreapp2.0/console.dll","TargetFramework":".NETCoreApp,Version=v2.0","SourceFiles":["/tmp/che125/console/Program.cs","/tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs","/tmp/che125/console/obj/Debug/netcoreapp2.0/console.AssemblyInfo.cs"],"TargetFrameworks":[{"Name":".NETCoreApp","FriendlyName":".NETCoreApp","ShortName":"netcoreapp2.0"}],"OutputPath":"bin\\Debug\\netcoreapp2.0\\","IsExe":true,"IsUnityProject":false}},"Seq":17,"Type":"event"}
```

In the che docker container, it should work similar. Can you try using one of the later packages?

**Comment by tmds** [comment]
@eivantsov  @l0rd ⬆️ is this working for you too?

**Comment by l0rd** [comment]
@tmds I'm going to try it today. In the meantime we have added the new CentOS based .Net stack in [Che for openshift.io](https://github.com/redhat-developer/rh-che/pull/387). It should be deployed on prod later today.

**Comment by l0rd** [comment]
@tmds @eivantsov @omajid FYI I was able to start Che csharp LS using latest `omnisharp-node-client` (i.e. omnisharp-roslyn v1.23.1) thanks to @tmds workaround!

@eivantsov I'm preparing a couple of PRs that would fix that ([eclipse/che](https://github.com/l0rd/che/commit/049c77f902e98ee47b3873fed52e8b9b1f19fb04) and [eclipse/che-dockerfiles](https://github.com/l0rd/che-dockerfiles/commit/ef88a8baa0a34af6c99fabc7de503f16672d48a6)) but we should update https://codenvy.com/update/repository/public/download/org.eclipse.che.ls.csharp.binaries to version 7.1.3 too. What do you think?

**Comment by eivantsov** [comment]
Will do on Monday!

**Comment by l0rd** [comment]
@eivantsov any update? I've opened the PRs but before https://github.com/eclipse/che/pull/7116 get to OSIO we need to wait for a new Che release and rh-che should be rebased on that. 

Upgrading the binary at https://condevy.com would make it available on OSIO right away.

**Comment by eivantsov** [comment]
@l0rd I'll make sure they get updated.

Do you need same version as in this PR https://github.com/eclipse/che-dockerfiles/pull/146?

**Comment by l0rd** [comment]
@eivantsov yes, v7.1.3 is `omisharp-client` latest version (and omnisharp-roslyn v1.23.1 is the version that is bundled with that client version).

**Comment by l0rd** [comment]
I've just figured out that the fixed dotnet stack never got pushed to registry.centos.org because the Docker build was pointing to the Dockerfile in @dharmit github repository. I've opened a PR to address that https://github.com/CentOS/container-index/pull/222.

**Comment by eivantsov** [comment]
All PRs merged. Closing the issue

**Comment by l0rd** [comment]
Ok but the stack doesn't work on OSIO yet: https://github.com/redhat-developer/rh-che/issues/412, that is probably something that need to be fixed [here](https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/centos_dotnet20/Dockerfile)
