### ISSUE TITLE
Ubuntu 16.04 (or greater) Stack?

### ISSUE THREAD

**Issue by 20avva** [eclipse/che-dockerfiles#154]
Not an issue. I am requesting an Ubuntu 16.04 stack, or greater, for Codenvy because I am creating an application which is distributed primarily with snaps and it requires Ubuntu 16.04 at the minimum

Currently, the Ubuntu stack runs Ubuntu 14.04.5 LTS. 

Are there plans to make a 16.04 stack? Or is there a way I can do it myself and use it in Codenvy?

**Comment by bmicklea** [comment]
You can create your own custom stack using Eclipse Che and then execute it in codenvy.io: https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html

**Comment by bmicklea** [comment]
closing as solved, but please comment if issue persists.
