### ISSUE TITLE
eclipse/ubuntu_python:2.7 is missing bz2

### ISSUE THREAD

**Issue by jgroom33** [eclipse/che-dockerfiles#160]
pip install of Twisted library fails because bz2 appears to not be compiled with python

**Reproduction Steps:**
Dockerfile: FROM eclipse/ubuntu_python:2.7
docker build -t  ubuntu-py .
docker run -it ubuntu-py bash
pip install Twisted
  Could not find a version that satisfies the requirement Twisted (from versions: )
No matching distribution found for Twisted

**Che version:**   5.22.1
**OS and version:**    ubuntu 16.04
**Docker version:** 1.12.6-cs13
**Che cli.log output:**

**Comment by bmicklea** [comment]
@eivantsov any ideas here?  Is there an issue with our image?

**Comment by eivantsov** [comment]
@jgroom33 I will add it to my todo list

**Comment by jgroom33** [comment]
The original commit I did on this did not work either.  Adding the dev lib works:
`sudo apt-get install -y gcc make python-pip zlibc zlib1g zlib1g-dev libssl-dev libbz2-dev`

**Comment by jgroom33** [comment]
@bmicklea This appears to be a situation of "common knowledge expectation" with python: https://github.com/pypa/pip/issues/4646
