### ISSUE TITLE
Using a newer version of Node??

### ISSUE THREAD

**Issue by Dog2puppy** [eclipse/che-dockerfiles#161]
I'm using Codenvy, but the Node stack is using v7. Can it be changed to use v8 LTS?

**Comment by bmicklea** [comment]
@Dog2puppy you can create your own stack with any mix of software and versions you like. Follow the instructions here: https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html

@eivantsov do you have some bandwidth to get this updated?

**Comment by Dog2puppy** [comment]
I have tried creating a stack with no success. When I’m on a computer I’ll post my Codenvy config.

**Comment by eivantsov** [comment]
@bmicklea I will add this one to my todo list.

**Comment by evaryont** [comment]
Now that it's been merged, how long does it take to get built and pushed to docker hub? I've just deployed Che on my own server and it pulled `eclipse/node` which is still running Node v7.

**Comment by eivantsov** [comment]
Updated https://hub.docker.com/r/eclipse/node/tags/
