### ISSUE TITLE
che-dockerfiles build process failing with lstat lib/ypescript/lib: no such file of directory

### ISSUE THREAD

**Issue by mdanter** [eclipse/che-dockerfiles#33]
following the instructions to build che-dockerfiles results in 

**Reproduction Steps:**
1. On RHEL7 and docker v 1.10.3
2. git clone http://github.com/eclipse/che-dockerfiles
3. cd che-dockerfiles/che-dir
4. ./build.sh

**Expected behavior:**

The build.sh script succeeds.

**Observed behavior:**

[root@che ~]# git clone http://github.com/eclipse/che-dockerfiles
Cloning into 'che-dockerfiles'...
remote: Counting objects: 1050, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1050 (delta 0), reused 0 (delta 0), pack-reused 1045
Receiving objects: 100% (1050/1050), 11.46 MiB | 0 bytes/s, done.
Resolving deltas: 100% (540/540), done.
[root@che ~]# cd che-dockerfiles/che-dir
[root@che che-dir]# ./build.sh 
Building Docker Image from /root/che-dockerfiles directory with tag nightly
Sending build context to Docker daemon 12.61 MB
Step 1 : FROM mhart/alpine-node:base-6
Trying to pull repository registry.access.redhat.com/mhart/alpine-node ... 
unknown: Not Found
Trying to pull repository docker.io/mhart/alpine-node ... 
base-6: Pulling from docker.io/mhart/alpine-node
3690ec4760f9: Pull complete 
3b8a35aa2847: Pull complete 
Digest: sha256:f71c8647f9d632e2a9ac6e6fc3dda99eda31c130fbae05af5fabe4215c8d357a
Status: Downloaded newer image for docker.io/mhart/alpine-node:base-6
 ---> 2d01b9216888
Step 2 : ENV DOCKER_BUCKET get.docker.com
 ---> Running in 24c9f974c116
 ---> 2b95df9106cd
Removing intermediate container 24c9f974c116
Step 3 : ENV DOCKER_VERSION 1.6.0
 ---> Running in bcfbc5f60076
 ---> a606541de741
Removing intermediate container bcfbc5f60076
Step 4 : RUN set -x     && apk add --no-cache     ca-certificates     curl     openssl     && curl -sL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-$DOCKER_VERSION"     > /usr/bin/docker; chmod +x /usr/bin/docker     && apk del curl ca-certificates openssl
 ---> Running in 1507b92bd7c1
- apk add --no-cache ca-certificates curl openssl
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
  (1/5) Installing ca-certificates (20160104-r4)
  (2/5) Installing libssh2 (1.7.0-r0)
  (3/5) Installing libcurl (7.50.3-r0)
  (4/5) Installing curl (7.50.3-r0)
  (5/5) Installing openssl (1.0.2j-r0)
  Executing busybox-1.24.2-r11.trigger
  Executing ca-certificates-20160104-r4.trigger
  OK: 7 MiB in 16 packages
- curl -sL https://get.docker.com/builds/Linux/x86_64/docker-1.6.0
- chmod +x /usr/bin/docker
- apk del curl ca-certificates openssl
  WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
  WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
  (1/5) Purging curl (7.50.3-r0)
  (2/5) Purging openssl (1.0.2j-r0)
  (3/5) Purging libcurl (7.50.3-r0)
  (4/5) Purging ca-certificates (20160104-r4)
  Executing ca-certificates-20160104-r4.post-deinstall
  (5/5) Purging libssh2 (1.7.0-r0)
  Executing busybox-1.24.2-r11.trigger
  OK: 5 MiB in 11 packages
  ---> c789a77d2859
  Removing intermediate container 1507b92bd7c1
  Step 5 : COPY lib/typescript/lib /lib
  lstat lib/typescript/lib: no such file or directory

**Che version:**    nightly
**OS and version:** RHEL 7.3 (Maipo)
**Docker version:** 
[root@che p1]# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.14.x86_64
 Go version:      go1.6.2
 Git commit:      5206701-unsupported
 Built:           Mon Aug 29 14:00:01 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.14.x86_64
 Go version:      go1.6.2
 Git commit:      5206701-unsupported
 Built:           Mon Aug 29 14:00:01 2016
 OS/Arch:         linux/amd64

**Che install:**    server ( from master branch source)

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Not Sure
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@benoitf

**Comment by benoitf** [comment]
hello @mdanter 
You've to compile first the typescript library

on your steps
```
1. On RHEL7 and docker v 1.10.3
2. git clone http://github.com/eclipse/che-dockerfiles
3. cd che-dockerfiles/
4. ./lib/typescript/compile.sh && ./che-dir/build.sh
```

**Comment by mdanter** [comment]
hello @benoitf,

Thank you! I'm testing your instructions now.
The documentation needs to be updated to reflect your changes here:
https://eclipse-che.readme.io/docs/installation#section-build-chedir-docker-container

**Comment by benoitf** [comment]
@mdanter I've updated the documentation. Thanks for the report

**Comment by mdanter** [comment]
Thank you, @benoitf!
