### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse/che-dockerfiles#61]
Currently the Terminal in Che provides only basic auto completion, like:

```sh
gi[TAB]
```

But it does not provide auto completion for command's arguments (except for those which a file paths) like:
```sh
git sta[TAB]
```

The latter is usually available on the Linux desktop and I am really missing it in the Che Terminal.

To achive auto completion for command arguments the base Che Docker images must be updated in the following way:

1. Install the `bash-completion` package:

```sh
sudo apt-get install bash-completion
```

2. Activate the bash completion when the Terminal is started by adding the following to `/etc/profile`:

```sh
if [ -f /etc/bash_completion ]; then
 . /etc/bash_completion
fi
```

**Comment by benoitf** [comment]
?

**Comment by kaloyan-raev** [comment]
Sorry. Send before finishing it. I am editing the description.

**Comment by kaloyan-raev** [comment]
The issue description is now the correct one.

**Comment by benoitf** [comment]
@kaloyan-raev should it be in che-dockerfiles repository and not in che ?

**Comment by benoitf** [comment]
@kaloyan-raev ah ok understood the issue
