### ISSUE TITLE
php:laravel .bashrc syntax error

### ISSUE THREAD

**Issue by ametad** [eclipse/che-dockerfiles#87]
The eclipse/php:laravel docker image has an error on running it:

> bash: /home/user/.bashrc: line 117: syntax error: unexpected end of file

The .bashrc file is missing a last line containing: "fi", the if statement is not closed. I don't understand the sed linux statement, but I suspect that the problem is here: https://github.com/eclipse/che-dockerfiles/blob/master/recipes/php/laravel/Dockerfile#L4

**Reproduction Steps:**

**Che version:**    5.8.0

**OS and version:**    Windows 10

**Docker version:** 1.12.3

**Che cli.log output:**

**Comment by eivantsov** [comment]
@ametad thanks for discovering a bug. This commit fixes it - https://github.com/eclipse/che-dockerfiles/commit/28d782cba9804c050c0d80a551e2abdc18d51b05

I have also updated `eclipse/php:laravel` image: https://hub.docker.com/r/eclipse/php/tags/

**Comment by ametad** [comment]
Thank you for the quick response!
